### PR TITLE
noarch

### LINKED ISSUE #4: convert to noarch: python
We should be able to convert this feedstock to `noarch: python`

Here's the PR which converted cylc-flow - https://github.com/conda-forge/cylc-flow-feedstock/pull/33

* Go throught the noarch checklist https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-builds
* Add the `__unix` psudo dependency.
* Convert to noarch.

This can be done *before* the 8.0rc1 release, follow the checklist in the PR description and increment the build number.

### PR DESCRIPTION
**Pull request by MetRonnie**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Closes #4

c.f. https://github.com/conda-forge/cylc-flow-feedstock/pull/33

### CODE REVIEW

**Comment by MetRonnie** [comment]
@conda-forge-admin please rerender

**Review by oliver-sanders — APPROVED** [review]

**Comment by wxtim** [comment]
@MetRonnie - Can I conda install as if from the recipe created by your fork?
Can you tell me how.
Are there any other tests that I can/should run?

**Comment by MetRonnie** [comment]
I think you have to build in order to then install. But I have been unable to build cylc-flow-feedstock locally on VLD in the past. So I think we're mainly going by the CI here

**Comment by oliver-sanders** [comment]
If you look lower down the recipe there are some basic tests to make sure that the relevant bits are still there.

**Review by wxtim — APPROVED** [review]

**Pull request merged**
